[app]
name = "Project Name"
version = "0.1.0"

[server]
host = "127.0.0.1"
port = 8080

[server.cors]
allowed_origins = ["*"]

[server.ssl]
enabled = false
cert_path = "path/to/cert.pem"
key_path = "path/to/key.pem"

[postgres]
host = "localhost"
port = 5432
user = "user"
password = "password"
database = "myapp"

[mongo]
url = "mongodb://localhost:27017"
database = "myapp"

[logs]
level = "debug"
output = "file"

[mail]
smtp_server = "smtp.example.com"
smtp_port = 587
smtp_user = "user@example.com"
smtp_password = "password"

[auth]
jwt_secret = "your_jwt_secret"
jwt_access_ttl = 600
jwt_refresh_ttl = 3600

[crypto]
hash_secret = "your_hash_secret"
salt = "your_salt"

[google]
client_id = "your_google_client_id"
client_secret = "your_google_client_secret"

[twitter]
api_key = "your_twitter_api_key"
api_secret_key = "your_twitter_api_secret_key"
